# Generated by Django 5.1.3 on 2024-11-27 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the full name of the author.', max_length=255, verbose_name='Name')),
                ('birth_date', models.DateField(blank=True, help_text="Enter the author's date of birth (format: YYYY-MM-DD).", null=True, verbose_name='Birth Date')),
                ('nationality', models.CharField(blank=True, help_text='Enter the nationality of the author.', max_length=100, null=True, verbose_name='Nationality')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book.', max_length=255, verbose_name='Title')),
                ('publication_date', models.DateField(blank=True, help_text='Enter the publication date of the book (format: YYYY-MM-DD).', null=True, verbose_name='Publication Date')),
                ('genre', models.CharField(blank=True, help_text='Enter the genre of the book (e.g., Historical Fiction).', max_length=100, null=True, verbose_name='Genre')),
                ('author', models.ForeignKey(help_text='Select the author of the book.', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myapp.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-publication_date', 'title'],
            },
        ),
    ]
